[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Set VITE_API_BASE as an environment variable in Netlify dashboard
# The actual backend URL will be configured in Netlify's environment variables
